import type { ClubMatch, MatchCallup, Player, TrainingSession, VolleyballEvent } from "./types";

function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}

function dateOffsetIso(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const seedPlayers: Player[] = [
  {
    id: "p-1",
    name: "Ramirez",
    number: "7",
    aliases: ["ramírez", "ramirez"],
    position: "Punta",
    category: "Sub-18",
    status: "active",
    phone: "+56 9 5555 0001",
    guardianName: "Carolina Ramirez",
    guardianPhone: "+56 9 1111 1111",
  },
  {
    id: "p-2",
    name: "Soto",
    number: "12",
    aliases: ["soto"],
    position: "Opuesto",
    category: "Sub-18",
    status: "active",
    guardianName: "Patricia Soto",
    guardianPhone: "+56 9 1111 2222",
  },
  {
    id: "p-3",
    name: "Martin",
    number: "4",
    aliases: ["martín", "martin"],
    position: "Central",
    category: "Sub-18",
    status: "active",
    guardianName: "Andrea Martin",
    guardianPhone: "+56 9 1111 3333",
  },
  {
    id: "p-4",
    name: "Vargas",
    number: "9",
    aliases: ["vargas"],
    position: "Armadora",
    category: "Adulto",
    status: "active",
    phone: "+56 9 5555 0004",
  },
  {
    id: "p-5",
    name: "Núñez",
    number: "2",
    aliases: ["nunez", "núñez"],
    position: "Líbero",
    category: "Adulto",
    status: "active",
    phone: "+56 9 5555 0005",
  },
  {
    id: "p-6",
    name: "Castro",
    number: "5",
    aliases: ["castro"],
    position: "Punta",
    category: "Adulto",
    status: "injured",
    phone: "+56 9 5555 0006",
    notes: "Tobillo derecho",
  },
  {
    id: "p-7",
    name: "Bravo",
    number: "8",
    aliases: ["bravo"],
    position: "Central",
    category: "Sub-18",
    status: "active",
    guardianName: "Felipe Bravo",
    guardianPhone: "+56 9 1111 4444",
  },
  {
    id: "p-8",
    name: "Lagos",
    number: "10",
    aliases: ["lagos"],
    position: "Opuesto",
    category: "Adulto",
    status: "active",
    phone: "+56 9 5555 0008",
  },
];

export const seedMatches: ClubMatch[] = [
  {
    id: "m-1",
    date: dateOffsetIso(2),
    time: "19:30",
    opponent: "Cóndores",
    location: "Gimnasio Municipal",
    competition: "Liga Regional",
    status: "scheduled",
  },
  {
    id: "m-2",
    date: dateOffsetIso(7),
    time: "20:00",
    opponent: "Tigres del Sur",
    location: "Polideportivo Central",
    competition: "Liga Regional",
    status: "scheduled",
  },
  {
    id: "m-3",
    date: todayIso(),
    time: "18:00",
    opponent: "Halcones",
    location: "Cancha Club",
    competition: "Amistoso",
    status: "live",
  },
  {
    id: "m-4",
    date: dateOffsetIso(-5),
    time: "19:00",
    opponent: "Pumas",
    location: "Gimnasio Norte",
    competition: "Liga Regional",
    status: "finished",
    notes: "Victoria 3-1",
  },
];

export const seedCallups: MatchCallup[] = [
  {
    matchId: "m-1",
    availability: {
      "p-1": "available",
      "p-2": "available",
      "p-3": "maybe",
      "p-4": "available",
      "p-5": "pending",
      "p-7": "available",
      "p-8": "unavailable",
    },
    notes: "Confirmar líbero antes del partido",
  },
  {
    matchId: "m-2",
    availability: {
      "p-1": "pending",
      "p-2": "pending",
      "p-4": "available",
      "p-5": "pending",
      "p-7": "pending",
    },
  },
  {
    matchId: "m-3",
    availability: {
      "p-1": "available",
      "p-2": "available",
      "p-3": "available",
      "p-4": "available",
      "p-5": "available",
      "p-7": "available",
    },
  },
];

export const seedTrainingSessions: TrainingSession[] = [
  {
    id: "t-1",
    date: todayIso(),
    time: "18:00",
    focus: "Saque y recepción",
    location: "Cancha 1",
    loads: {
      "p-1": { present: true, minutes: 90, rpe: 6, fatigue: 3, pain: 0 },
      "p-2": { present: true, minutes: 75, rpe: 7, fatigue: 4, pain: 1 },
      "p-3": { present: false, minutes: 0, rpe: 0, fatigue: 0, pain: 0, notes: "Ausente" },
      "p-4": { present: true, minutes: 90, rpe: 5, fatigue: 3, pain: 0 },
      "p-5": { present: true, minutes: 90, rpe: 6, fatigue: 2, pain: 0 },
      "p-7": { present: true, minutes: 80, rpe: 7, fatigue: 4, pain: 1 },
      "p-8": { present: true, minutes: 90, rpe: 8, fatigue: 5, pain: 2 },
    },
  },
  {
    id: "t-2",
    date: dateOffsetIso(-2),
    time: "18:00",
    focus: "Ataque y bloqueo",
    location: "Cancha 1",
    loads: {
      "p-1": { present: true, minutes: 100, rpe: 7, fatigue: 4, pain: 0 },
      "p-2": { present: true, minutes: 100, rpe: 8, fatigue: 5, pain: 0 },
      "p-3": { present: true, minutes: 90, rpe: 6, fatigue: 3, pain: 0 },
      "p-4": { present: true, minutes: 100, rpe: 6, fatigue: 4, pain: 0 },
      "p-5": { present: true, minutes: 100, rpe: 7, fatigue: 4, pain: 1 },
    },
  },
];

export const seedEvents: VolleyballEvent[] = [
  {
    id: "e-1",
    sequence: 1,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-1",
    playerName: "Ramirez",
    actionType: "serve",
    result: "ace",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-2",
    sequence: 2,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-2",
    playerName: "Soto",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-3",
    sequence: 3,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-3",
    playerName: "Martin",
    actionType: "block",
    result: "stuff",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-4",
    sequence: 4,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-4",
    playerName: "Vargas",
    actionType: "set",
    result: "positive",
    source: "manual",
  },
  {
    id: "e-5",
    sequence: 5,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-5",
    playerName: "Núñez",
    actionType: "dig",
    result: "perfect",
    source: "manual",
  },
  {
    id: "e-6",
    sequence: 6,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-1",
    playerName: "Ramirez",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-7",
    sequence: 7,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-2",
    playerName: "Soto",
    actionType: "serve",
    result: "ace",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-8",
    sequence: 8,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-7",
    playerName: "Bravo",
    actionType: "block",
    result: "stuff",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-9",
    sequence: 9,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-1",
    playerName: "Ramirez",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-10",
    sequence: 10,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-3",
    playerName: "Martin",
    actionType: "attack",
    result: "error",
    pointFor: "away",
    source: "manual",
  },
  {
    id: "e-11",
    sequence: 11,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-2",
    playerName: "Soto",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-12",
    sequence: 12,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-4",
    playerName: "Vargas",
    actionType: "assist",
    result: "positive",
    source: "manual",
  },
  {
    id: "e-13",
    sequence: 13,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-1",
    playerName: "Ramirez",
    actionType: "serve",
    result: "in_play",
    source: "manual",
  },
  {
    id: "e-14",
    sequence: 14,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-7",
    playerName: "Bravo",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
  {
    id: "e-15",
    sequence: 15,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-5",
    playerName: "Núñez",
    actionType: "dig",
    result: "perfect",
    source: "manual",
  },
  {
    id: "e-16",
    sequence: 16,
    createdAt: new Date().toISOString(),
    matchId: "m-3",
    teamSide: "home",
    playerId: "p-1",
    playerName: "Ramirez",
    actionType: "attack",
    result: "kill",
    pointFor: "home",
    source: "manual",
  },
];

export const seedClubName = "Sporti Volley Club";
